import pandas as pd
from datetime import datetime
import os
import boto3
import plotly.graph_objects as go
from plotly.subplots import make_subplots
import talib
import warnings
import io

warnings.simplefilter(action='ignore', category=FutureWarning)

# Initialize S3 client globally
s3_client = boto3.client('s3')
bucket_name = os.environ['BUCKET_NAME']

def handler(event, context):
    symbol = event.get('symbol', 'AAPL')
    print(f"Starting analysis for {symbol}...")
    
    # Retrieve the path generated by the ingestor from the Step Functions event
    # Fallback to today's date if testing manually
    ts0 = datetime.now().strftime("%Y-%m-%d")
    data_path = event.get('ingestion_result', {}).get('data_path', f"raw_data/{ts0}/")
    
    ts0_out, signal, signal2, lastClose = plotChart(symbol, data_path, ts0)
    
    return {
        "symbol": symbol,
        "date": ts0_out,
        "signal": signal,
        "close_price": str(lastClose),
        "chart_url": f"s3://{bucket_name}/charts/{ts0_out}/{signal2}{symbol}.png" if signal else "None"
    }

def plotChart(symbol, data_path, ts0): 
    # ---------------------------------------------------------
    # 1. READ FROM DATA LAKE
    # ---------------------------------------------------------
    s3_key = f"{data_path}{symbol}.csv"
    try:
        response = s3_client.get_object(Bucket=bucket_name, Key=s3_key)
        df = pd.read_csv(io.BytesIO(response['Body'].read()))
    except Exception as e:
        print(f"Error loading {symbol} from S3: {e}")
        return ts0, "", "", 0

    # The ingestor saves Date as YYYYMMDD string, convert it back to datetime for Plotly
    df['Date'] = pd.to_datetime(df['Date'], format='%Y%m%d')
    df['Vol'] = df['Volume']
    
    # Calculate Indicators on the FULL dataset
    df['RSI4'] = talib.RSI(df["Close"], timeperiod=4)
    df['CCI20'] = talib.CCI(df["High"], df["Low"], df["Close"], timeperiod=20)
    df['SMA50'] = talib.SMA(df["Close"], timeperiod=50)
    df['SMA200'] = talib.SMA(df["Close"], timeperiod=200)
    df['BBUpper'], df['BBMid'], df['BBLow'] = talib.BBANDS(df["Close"], timeperiod=20, nbdevup=2, nbdevdn=2, matype=0)

    # Drop NaNs and slice strictly to the last 5 years (approx 1260 trading days)
    df = df.dropna().reset_index(drop=True)
    df = df.tail(1260).reset_index(drop=True) # FIX 1: Slices the dataframe for clean lines

    # ---------------------------------------------------------
    # 2. PLOTLY CHART GENERATION
    # ---------------------------------------------------------
    chart_data = go.Candlestick(x=df['Date'], open=df['Open'], high=df['High'], low=df['Low'], close=df['Close'], showlegend=False, line=dict(width=1))
    fig = make_subplots(rows=4, cols=1, shared_xaxes=True, vertical_spacing=0.02, row_width=[0.2, 0.2, 0.1, 0.5])
    fig.add_trace(chart_data, row=1, col=1)
    
    # SMAs
    fig.add_trace(go.Scatter(x=df['Date'], y=df['SMA50'], mode='lines', name='SMA50', line=dict(color="#0000FF", width=1), showlegend=False), row=1, col=1)
    fig.add_trace(go.Scatter(x=df['Date'], y=df['SMA200'], mode='lines', name='SMA200', line=dict(color="#FF0000", width=1), showlegend=False), row=1, col=1)
    
    # Bollinger Bands
    fig.add_trace(go.Scatter(x=df['Date'], y=df['BBUpper'], mode='lines', line=dict(color="#888888", width=1, dash="dot"), showlegend=False), row=1, col=1)
    fig.add_trace(go.Scatter(x=df['Date'], y=df['BBMid'], mode='lines', line=dict(color="#0000FF", width=1, dash="solid"), showlegend=False), row=1, col=1)
    fig.add_trace(go.Scatter(x=df['Date'], y=df['BBLow'], mode='lines', line=dict(color="#888888", width=1, dash="dot"), showlegend=False), row=1, col=1)
    
    # Volume (Fixed line borders to prevent washout)
    fig.add_trace(go.Bar(
        x=df['Date'], 
        y=df['Vol'], 
        showlegend=False,
        marker=dict(color='lightpink', line=dict(width=0)) # FIX 2: Removes the microscopic gray borders
    ), row=2, col=1)
    
    # RSI
    fig.add_trace(go.Scatter(x=df['Date'], y=df['RSI4'], mode='lines', line_color="#000000", showlegend=False), row=3, col=1)
    for y_val in [25, 55, 75]:
        fig.add_hline(y=y_val, line_dash="dot", row=3, col=1, line_color="#000000", line_width=1)
        
    # CCI
    fig.add_trace(go.Scatter(x=df['Date'], y=df['CCI20'], mode='lines', line_color="#000000", showlegend=False), row=4, col=1)
    for y_val in [-100, 0, 100]:
        fig.add_hline(y=y_val, line_dash="dot", row=4, col=1, line_color="#000000", line_width=1)

    # Buy Signal Arrows (Fixed dynamic offset)
    arrow_dates = df.loc[(df['RSI4'] < 25) & (df['Close'] > df['SMA200']), 'Date']
    arrow_lows = df.loc[(df['RSI4'] < 25) & (df['Close'] > df['SMA200']), 'Low'] - (df['Low'] * 0.02)
    
    fig.add_trace(go.Scatter(
        x=arrow_dates, y=arrow_lows, mode='markers',
        marker=dict(symbol='triangle-up', size=12, color='green'),
        showlegend=False
    ), row=1, col=1)
    
    # Determine Signal and pull latest values
    lastClose = round(df['Close'].iloc[-1], 2)
    lastSMA200 = round(df['SMA200'].iloc[-1], 2)
    lastRSI4 = round(df['RSI4'].iloc[-1], 2)
    lastCCI20 = round(df['CCI20'].iloc[-1], 2) # Added CCI logic back for the title
    
    signal, signal2 = "", ""
    titleColor = "black"
    
    if lastClose > lastSMA200 and lastRSI4 < 25:
        signal = "---BUY RSI4---"
        signal2 = "___BUY RSI4___"
        titleColor = "green"

    if signal2 != "":
        # FIX 3: Rebuilt your dynamic string and applied original layout preferences
        dynamic_title = f"{ts0}          {symbol}          Close: {lastClose}     SMA200: {lastSMA200}          RSI4: {lastRSI4}          CCI20: {lastCCI20}          {signal}"
        
        fig.update_layout(
            title=dynamic_title,
            title_font_family="Arial", 
            title_font_color=titleColor,
            font=dict(size=33),
            xaxis_rangeslider_visible=False,
            height=1500
        )
        
        # Saves to S3 in high-res just like your local script did
        img_bytes = fig.to_image(format="png", engine="kaleido", width=3000, height=2000)
        s3_client.put_object(
            Bucket=bucket_name,
            Key=f"charts/{ts0}/{signal2}{symbol}.png",
            Body=img_bytes,
            ContentType='image/png'
        )
        print(f"Signal found: {signal}. Chart saved to S3.")
    else:
        print(f"No signal generated for {symbol}. Chart bypassed.")
        
    return ts0, signal, signal2, lastClose