import pandas as pd
from datetime import datetime
import os
import boto3
import plotly.graph_objects as go
from plotly.subplots import make_subplots
import talib
import warnings
import io

# Suppress pandas FutureWarnings to keep Lambda CloudWatch logs clean
warnings.simplefilter(action='ignore', category=FutureWarning)

# Initialize AWS clients globally outside the handler.
# This takes advantage of Lambda "warm starts" to reuse the connection across multiple invocations.
s3_client = boto3.client('s3')
bucket_name = os.environ['BUCKET_NAME']

def handler(event, context):
    """
    Lambda entry point for the Analyzer Step.
    Expected 'event': A dictionary passed from the Map state in Step Functions,
    containing at least the 'symbol' and the 'ingestion_result' payload.
    """
    symbol = event.get('symbol', 'AAPL')
    print(f"Starting analysis for {symbol}...")
    
    # Retrieve the S3 path generated by the ingestor from the Step Functions event.
    # Fallback to today's date structure to allow manual/local testing.
    ts0 = datetime.now().strftime("%Y-%m-%d")
    data_path = event.get('ingestion_result', {}).get('data_path', f"raw_data/{ts0}/")
    
    # Execute the core analysis and charting logic
    ts0_out, signal, signal2, lastClose = plotChart(symbol, data_path, ts0)
    
    # Return a structured dictionary. This becomes the payload passed to the 
    # Publisher Lambda and eventually aggregated by the Aggregator Lambda.
    return {
        "symbol": symbol,
        "date": ts0_out,
        "signal": signal,
        "close_price": str(lastClose),
        # Only provide a valid S3 URL if a chart was actually generated (i.e., a signal triggered)
        "chart_url": f"s3://{bucket_name}/charts/{ts0_out}/{signal2}{symbol}.png" if signal else "None"
    }

def plotChart(symbol, data_path, ts0): 
    # ---------------------------------------------------------
    # 1. READ FROM DATA LAKE & PREPARE DATA
    # ---------------------------------------------------------
    s3_key = f"{data_path}{symbol}.csv"
    try:
        # Stream the CSV directly from S3 into a Pandas DataFrame using io.BytesIO.
        # This avoids writing to the Lambda's temporary disk space (/tmp).
        response = s3_client.get_object(Bucket=bucket_name, Key=s3_key)
        df = pd.read_csv(io.BytesIO(response['Body'].read()))
    except Exception as e:
        print(f"Error loading {symbol} from S3: {e}")
        # Return empty signals if data is missing or corrupted
        return ts0, "", "", 0

    # The ingestor saves Date as a YYYYMMDD string (e.g., "20231024").
    # Convert it back to a proper datetime object so Plotly can format the X-axis correctly.
    df['Date'] = pd.to_datetime(df['Date'], format='%Y%m%d')
    df['Vol'] = df['Volume']
    
    # RSI (Relative Strength Index) - 4-period for mean reversion
    df['RSI4'] = talib.RSI(df["Close"], timeperiod=4)
    # CCI (Commodity Channel Index) - 20-period for mean reversion
    df['CCI20'] = talib.CCI(df["High"], df["Low"], df["Close"], timeperiod=20)
    # Simple Moving Averages for medium (50) and long-term (200) trend identification
    df['SMA50'] = talib.SMA(df["Close"], timeperiod=50)
    df['SMA200'] = talib.SMA(df["Close"], timeperiod=200)
    # Bollinger Bands for volatility and mean reversion
    df['BBUpper'], df['BBMid'], df['BBLow'] = talib.BBANDS(df["Close"], timeperiod=20, nbdevup=2, nbdevdn=2, matype=0)

    # Drop the initial rows where the 200-day SMA was calculating (will be NaN).
    df = df.dropna().reset_index(drop=True)
    
    # Slices the dataframe strictly to the last 1260 rows (~5 years of trading days).
    # This prevents the chart from being too compressed.
    df = df.tail(1260).reset_index(drop=True) 

    # ---------------------------------------------------------
    # 2. PLOTLY CHART GENERATION
    # ---------------------------------------------------------
    # Setup the primary Candlestick trace
    chart_data = go.Candlestick(
        x=df['Date'], open=df['Open'], high=df['High'], 
        low=df['Low'], close=df['Close'], 
        showlegend=False, line=dict(width=1)
    )
    
    # Create a 4-panel vertical layout. 
    # row_width applies from BOTTOM to TOP in Plotly.
    # Heights: Candlestick (50%), Volume (10%), RSI (20%), CCI (20%)
    fig = make_subplots(
        rows=4, cols=1, shared_xaxes=True, 
        vertical_spacing=0.02, row_width=[0.2, 0.2, 0.1, 0.5]
    )
    
    # Panel 1: Price Action & Overlays
    fig.add_trace(chart_data, row=1, col=1)
    fig.add_trace(go.Scatter(x=df['Date'], y=df['SMA50'], mode='lines', name='SMA50', line=dict(color="#0000FF", width=1), showlegend=False), row=1, col=1)
    fig.add_trace(go.Scatter(x=df['Date'], y=df['SMA200'], mode='lines', name='SMA200', line=dict(color="#FF0000", width=1), showlegend=False), row=1, col=1)
    
    # Bollinger Bands
    fig.add_trace(go.Scatter(x=df['Date'], y=df['BBUpper'], mode='lines', line=dict(color="#888888", width=1, dash="dot"), showlegend=False), row=1, col=1)
    fig.add_trace(go.Scatter(x=df['Date'], y=df['BBMid'], mode='lines', line=dict(color="#0000FF", width=1, dash="solid"), showlegend=False), row=1, col=1)
    fig.add_trace(go.Scatter(x=df['Date'], y=df['BBLow'], mode='lines', line=dict(color="#888888", width=1, dash="dot"), showlegend=False), row=1, col=1)
    
    # Panel 2: Volume 
    # Set `line=dict(width=0)` to remove gray borders
    # which can cause high-density bar charts to render completely gray, washing out the pink.
    fig.add_trace(go.Bar(
        x=df['Date'], y=df['Vol'], showlegend=False,
        marker=dict(color='lightpink', line=dict(width=0)) 
    ), row=2, col=1)
    
    # Panel 3: RSI4 with Oversold/Overbought reference lines (25, 55, 75)
    fig.add_trace(go.Scatter(x=df['Date'], y=df['RSI4'], mode='lines', line_color="#000000", showlegend=False), row=3, col=1)
    for y_val in [25, 55, 75]:
        fig.add_hline(y=y_val, line_dash="dot", row=3, col=1, line_color="#000000", line_width=1)
        
    # Panel 4: CCI20 with standard deviation threshold lines (-100, 0, 100)
    fig.add_trace(go.Scatter(x=df['Date'], y=df['CCI20'], mode='lines', line_color="#000000", showlegend=False), row=4, col=1)
    for y_val in [-100, 0, 100]:
        fig.add_hline(y=y_val, line_dash="dot", row=4, col=1, line_color="#000000", line_width=1)

    # ---------------------------------------------------------
    # 3. HISTORICAL SIGNAL MARKERS
    # ---------------------------------------------------------
    # Trading Strategy: "Pullback in an Uptrend"
    # Find all historical dates where the long-term trend is UP (Close > SMA200),
    # but the short-term momentum is severely OVERSOLD (RSI4 < 25).
    arrow_dates = df.loc[(df['RSI4'] < 25) & (df['Close'] > df['SMA200']), 'Date']
    
    # Dynamically place the arrow 2% below the 'Low' of the day so it doesn't overlap the candlestick.
    arrow_lows = df.loc[(df['RSI4'] < 25) & (df['Close'] > df['SMA200']), 'Low'] - (df['Low'] * 0.02)
    
    fig.add_trace(go.Scatter(
        x=arrow_dates, y=arrow_lows, mode='markers',
        marker=dict(symbol='triangle-up', size=12, color='green'),
        showlegend=False
    ), row=1, col=1)
    
    # ---------------------------------------------------------
    # 4. CURRENT DAY SIGNAL EVALUATION & EXPORT
    # ---------------------------------------------------------
    # Extract the absolute latest metrics to evaluate if a signal triggered *today*
    lastClose = round(df['Close'].iloc[-1], 2)
    lastSMA200 = round(df['SMA200'].iloc[-1], 2)
    lastRSI4 = round(df['RSI4'].iloc[-1], 2)
    lastCCI20 = round(df['CCI20'].iloc[-1], 2)
    
    signal, signal2 = "", ""
    titleColor = "black"
    
    # Does the current day meet the strategy criteria?
    if lastClose > lastSMA200 and lastRSI4 < 25:
        signal = "---BUY RSI4---"
        signal2 = "___BUY RSI4___" # Used for filename sanitization
        titleColor = "green"

    # Only spend compute/time exporting the chart if a signal was actually found today.
    # Rendering images via Kaleido is the most CPU-intensive part of this Lambda.
    if signal2 != "":
        dynamic_title = f"{ts0}          {symbol}          Close: {lastClose}     SMA200: {lastSMA200}          RSI4: {lastRSI4}          CCI20: {lastCCI20}          {signal}"
        
        fig.update_layout(
            title=dynamic_title,
            title_font_family="Arial", 
            title_font_color=titleColor,
            font=dict(size=33),
            xaxis_rangeslider_visible=False, # Hides the messy default Plotly slider
            height=1500
        )
        
        # Convert the Plotly figure to a static PNG image in memory using the Kaleido engine
        img_bytes = fig.to_image(format="png", engine="kaleido", width=3000, height=2000)
        
        # Upload the generated chart directly to the S3 bucket
        s3_client.put_object(
            Bucket=bucket_name,
            Key=f"charts/{ts0}/{signal2}{symbol}.png",
            Body=img_bytes,
            ContentType='image/png'
        )
        print(f"Signal found: {signal}. Chart saved to S3.")
    else:
        print(f"No signal generated for {symbol}. Chart bypassed.")
        
    return ts0, signal, signal2, lastClose